services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.60.0-jammy
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - BASE_URL=${BASE_URL}
    command: >
      sh -c "
        yarn install &&
        yarn playwright test
      "